### ISSUE TITLE
Sync branding repository with database

### ISSUE THREAD

**Issue by TheRolfFR** [Faithful-Resource-Pack/Branding#3]
Hello,

Would it be nice to add an Action so that the images in this repository are synced with database subdomain inside branding folder, it would allow for easier CDN use.

(We ignore __old folder)

It can be a bad idea, tell me, I don't know. Tell me what you think.

**Comment by RobertRR11** [comment]
the branding in the database is not used anymore

**Comment by Juknum** [comment]
The branding in the database is still used with the bot, plus we have the possibility to resize images dynamically using the database url which is also used for the bot

And it would be so much easier to keep track of who added what & when to the branding folders

**Comment by RobertRR11** [comment]
> who added what & when

that is called git
